create table type_de_paiement (id int primary key, type_de_paiement int(12));
insert into type_de_paiement (id, type_de_paiement) values (0, 10);
insert into type_de_paiement (id, type_de_paiement) values (1, 20);
insert into type_de_paiement (id, type_de_paiement) values (2, 30);
insert into type_de_paiement (id, type_de_paiement) values (3, 40);
insert into type_de_paiement (id, type_de_paiement) values (4, 50);
insert into type_de_paiement (id, type_de_paiement) values (5, 60);
insert into type_de_paiement (id, type_de_paiement) values (6, 70);
insert into type_de_paiement (id, type_de_paiement) values (7, 603);
insert into type_de_paiement (id, type_de_paiement) values (8, 604);
insert into type_de_paiement (id, type_de_paiement) values (9, 605);
insert into type_de_paiement (id, type_de_paiement) values (10, 606);
insert into type_de_paiement (id, type_de_paiement) values (11, 607);
insert into type_de_paiement (id, type_de_paiement) values (12, 608);
insert into type_de_paiement (id, type_de_paiement) values (13, 609);
