#!/bin/bash
# @author: Dr.-Ing. XAVIER NOUNDOU

ALL_YEROTH_CODEBASE_CPP_FILES="${YEROTH_ERP_3_0_HOME_FOLDER}/yeroth-ALL-USER-ENABLING-ACTIONS-WINDOWS.TXT"

function generate_init_user_action_rights_txt 
{
	CURRENT_YEROTH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX="${1}"

	YEROTH_TEXT_TO_REPLACE_OR_FILE="${CURRENT_YEROTH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}-INIT-USER-ACTION-RIGHTS.txt"
	
	yeroth-GENERATE-FOR-FILE-CPP-USER-ENABLING-ACTION-CPP-COMMANDS.sh \
		-i "${YEROTH_TEXT_TO_REPLACE_OR_FILE}" \
		-o "${CURRENT_YEROTH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}-INIT-USER-ACTION-RIGHTS-cpp-COMMANDS.txt"
	
	YEROTH_TEXT_TO_PLACE_INSIDE_CODE="$(cat "${CURRENT_YEROTH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}-INIT-USER-ACTION-RIGHTS-cpp-COMMANDS.txt")"

	sed -i \
		"s|CONSTRUCTOR_USER_ACTION_RIGHTS|${YEROTH_TEXT_TO_PLACE_INSIDE_CODE}|g" \
		"${CURRENT_YEROTH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}.cpp"

	rm "${CURRENT_YEROTH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}-INIT-USER-ACTION-RIGHTS-cpp-COMMANDS.txt"
}

while read LINE; do
	LINE="${YEROTH_ERP_3_0_HOME_FOLDER}/${LINE}"
	generate_init_user_action_rights_txt "${LINE%%".cpp"}"
done < "$ALL_YEROTH_CODEBASE_CPP_FILES"

