/*
 * yeroth-erp-3-0-definition-file-folder.hpp
 *
 *      Author: DR.-ING. DIPL.-INF. XAVIER NOUMBISSI NOUNDOU
 */

#ifndef _YEROTH_ERP_3_0_DEFINITION_FILE_FOLDER_HPP_
#define _YEROTH_ERP_3_0_DEFINITION_FILE_FOLDER_HPP_

#define FOLDER_YEROTH_ERP_3_0_PRIVATE_CONFIGURATION 			":yeroth-erp-3-0-config"

#include "yeroth-erp-3-0-definition-user-manual.hpp"

#define FOLDER_YEROTH_ERP_3_0_SQL 																":yeroth-erp-3-0-sql"
#define FOLDER_YEROTH_ERP_3_0_TEMPLATES 													":yeroth-erp-3-0-templates"

#define FILE_YEROTH_ERP_3_0_PUBLIC_LOG_INFO 															"yeroth-erp-3-0.log"
#define FILE_YEROTH_ERP_3_0_PUBLIC_USER_PROPERTIES 											"yeroth-erp-3-0.properties"

#define FILE_YEROTH_ERP_3_0_USER_MANUAL_FR 					FOLDER_YEROTH_ERP_3_0_USER_DOC"/francais/yeroth-erp-3-0-software-system-uses.pdf"

#define FILE_YEROTH_ERP_3_0_SQL_TABLE_periodes_dappartenance_groupes_de_paie_hr \
		FOLDER_YEROTH_ERP_3_0_SQL"/create_table_PERIODES_DAPPARTENANCE_GROUPES_DE_PAIE_HR.sql"

#define FILE_YEROTH_ERP_3_0_SQL_TABLE_groupes_demployes_hr				FOLDER_YEROTH_ERP_3_0_SQL"/create_table_GROUPES_DEMPLOYES_HR.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_groupes_de_paie_hr					FOLDER_YEROTH_ERP_3_0_SQL"/create_table_GROUPES_DE_PAIE_HR.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_TYPE_DOPERATIONS_FINANCIERES	FOLDER_YEROTH_ERP_3_0_SQL"/create_table_typedoperations_financieres.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_OPERATIONS_COMPTABLES 			FOLDER_YEROTH_ERP_3_0_SQL"/create_table_operations_comptables.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_COMPTES_DOPERATIONS_COMPTABLES FOLDER_YEROTH_ERP_3_0_SQL"/create_table_comptes_doperations_comptables.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_COMPTES_BANCAIRES 					FOLDER_YEROTH_ERP_3_0_SQL"/create_table_comptes_bancaires.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_ENTREPRISE_INFO 						FOLDER_YEROTH_ERP_3_0_SQL"/create_table_entreprise_info.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_TYPE_DE_VENTE 							FOLDER_YEROTH_ERP_3_0_SQL"/create_table_typedevente.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_TYPE_DE_PAIEMENT 					FOLDER_YEROTH_ERP_3_0_SQL"/create_table_typedepaiement.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_PAIEMENTS 									FOLDER_YEROTH_ERP_3_0_SQL"/create_table_paiements.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_CREDIT_CARD_ISSUING_COMPANY 			FOLDER_YEROTH_ERP_3_0_SQL"/create_table_credit_card_issuing_company.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_INIT_CONFIGURATION 				FOLDER_YEROTH_ERP_3_0_SQL"/create_table_init_configurations.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_CONFIGURATIONS 						FOLDER_YEROTH_ERP_3_0_SQL"/create_table_configurations.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_ROLES 											FOLDER_YEROTH_ERP_3_0_SQL"/create_table_roles.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_USERS 											FOLDER_YEROTH_ERP_3_0_SQL"/create_table_users.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_TITRES 										FOLDER_YEROTH_ERP_3_0_SQL"/create_table_titres.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_LOCALISATIONS 							FOLDER_YEROTH_ERP_3_0_SQL"/create_table_localisations.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_CHARGES_FINANCIERES		FOLDER_YEROTH_ERP_3_0_SQL"/create_table_charges_financieres.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_ACHATS 										FOLDER_YEROTH_ERP_3_0_SQL"/create_table_achats.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_STOCKS 										FOLDER_YEROTH_ERP_3_0_SQL"/create_table_stocks.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_SERVICES_COMPLETES 				FOLDER_YEROTH_ERP_3_0_SQL"/create_table_services_completes.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_MARCHANDISES 							FOLDER_YEROTH_ERP_3_0_SQL"/create_table_marchandises.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_STOCKS_VENDU 							FOLDER_YEROTH_ERP_3_0_SQL"/create_table_stocks_vendu.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_STOCKS_SORTIES 						FOLDER_YEROTH_ERP_3_0_SQL"/create_table_stocks_sorties.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_ALERTES 										FOLDER_YEROTH_ERP_3_0_SQL"/create_table_alertes.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_REMISES 										FOLDER_YEROTH_ERP_3_0_SQL"/create_table_remises.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_CONDITIONS_ALERTES 				FOLDER_YEROTH_ERP_3_0_SQL"/create_table_conditions_alertes.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_COURRIERS_ALERTES 					FOLDER_YEROTH_ERP_3_0_SQL"/create_table_courriers_alertes.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_PROGRAMMES_DE_FIDELITES_CLIENTS	FOLDER_YEROTH_ERP_3_0_SQL"/create_table_programmes_de_fidelite_clients.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_GROUPES_DE_CLIENTS 				FOLDER_YEROTH_ERP_3_0_SQL"/create_table_groupes_de_clients.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_CLIENTS 										FOLDER_YEROTH_ERP_3_0_SQL"/create_table_clients.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_FOURNISSEURS 							FOLDER_YEROTH_ERP_3_0_SQL"/create_table_fournisseurs.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_IMPRIMANTERESEAU_RECUS_PETITS   FOLDER_YEROTH_ERP_3_0_SQL"/create_table_imprimantereseau_recus_petits.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_DBMS 											FOLDER_YEROTH_ERP_3_0_SQL"/create_table_dbms.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_DEPARTEMENTS_PRODUITS 			FOLDER_YEROTH_ERP_3_0_SQL"/create_table_departements_produits.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_CATEGORIES 								FOLDER_YEROTH_ERP_3_0_SQL"/create_table_categories.sql"
#define FILE_YEROTH_ERP_3_0_SQL_TABLE_LIGNES_BUDGETAIRES				FOLDER_YEROTH_ERP_3_0_SQL"/create_table_LIGNES_BUDGETAIRES.sql"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_1A_TEX 											FOLDER_YEROTH_ERP_3_0_TEMPLATES"/1a.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_BAR_DIAG_EN 								FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_bar-diag.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_BAR_DIAG_FR 								FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_bar-diag.tex"

#define FILE_YEROTH_CLIENT_LOYALTY_GROUPS_LISTING_TEMPLATE_FR  		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-lister-programmes-de-fidelite-GROUPES-clients.tex"
#define FILE_YEROTH_CLIENT_LOYALTY_GROUPS_LISTING_TEMPLATE_EN  		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-lister-programmes-de-fidelite-GROUPES-clients.tex"

#define FILE_YEROTH_CLIENT_LOYALTY_PROGRAM_LISTING_TEMPLATE_FR  	FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-lister-programmes-de-fidelite-clients.tex"
#define FILE_YEROTH_CLIENT_LOYALTY_PROGRAM_LISTING_TEMPLATE_EN  	FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-lister-programmes-de-fidelite-clients.tex"

#define FILE_YEROTH_LOYALTY_MEMBERSHIP_CARD_TEMPLATE_EN  					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_YEROTH_LOYALTY_MEMBERSHIP_CARD_TEMPLATE.tex"
#define FILE_YEROTH_LOYALTY_MEMBERSHIP_CARD_TEMPLATE_FR 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_YEROTH_LOYALTY_MEMBERSHIP_CARD_TEMPLATE.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_CLIENT_GROUP_HR_EN 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template_GROUPES_DUN_CLIENT.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_CLIENT_GROUP_HR_FR 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template_GROUPES_DUN_CLIENT.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_PAY_GROUP_HR_EN 							FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template_PAY_GROUP_LISTING.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_PAY_GROUP_HR_FR 							FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template_PAY_GROUP_LISTING.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_EMPLOYEES_GROUPS_HR_EN 			FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template_EMPLOYEE_GROUP_LISTING.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_EMPLOYEES_GROUPS_HR_FR 			FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template_EMPLOYEE_GROUP_LISTING.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_EMPLOYEE_GROUP_HR_EN 				FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template_GROUPES_DUN_EMPLOYE.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_EMPLOYEE_GROUP_HR_FR 				FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template_GROUPES_DUN_EMPLOYE.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_ZERO_VENTES_EN 							FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_ZERO_ventes.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_ZERO_VENTES_FR 							FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_ZERO_ventes.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_BAR_CHART_EN 								FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_bar-chart.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_BAR_CHART_FR 								FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_bar-chart.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_PIE_CHART_EN 								FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_pie-chart.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_PIE_CHART_FR 								FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_pie-chart.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_PURCHASE_ORDER_SHEET_EN 			FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-bon_de_COMMANDE.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_PURCHASE_ORDER_SHEET_FR 			FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-bon_de_COMMANDE.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_FINANCIAL_ACCOUNTING_REPORT_DATA_EN 		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-bilan-comptable.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_FINANCIAL_ACCOUNTING_REPORT_DATA_FR 		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-bilan-comptable.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_SUPPLIER_DATA_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-fiche-dun-fournisseur.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_SUPPLIER_DATA_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-fiche-dun-fournisseur.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_CUSTOMER_DATA_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-fiche-dun-client.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_CUSTOMER_DATA_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-fiche-dun-client.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_INVOICE_LARGE_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template_facture-grand.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_INVOICE_LARGE_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template_facture-grand.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_RECEIPT_SMALL_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template_recu-petit.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_RECEIPT_SMALL_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template_recu-petit.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_THREE_D_BARDIAG_EN 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-THREE_D_bardiag.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_THREE_D_BARDIAG_FR 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-THREE_D_bardiag.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_RECEIPT_LARGE_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template_recu-grand.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_RECEIPT_LARGE_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template_recu-grand.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_HISTORIQUE_DUN_STOCK_EN 				FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-historique-dun-stock.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_HISTORIQUE_DUN_STOCK_FR 				FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-historique-dun-stock.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTING_PAYMENTS_EN 				FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-journal-des-paiements.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTING_PAYMENTS_FR 				FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-journal-des-paiements.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTING_SALES_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-journal-des-ventes.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTING_SALES_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-journal-des-ventes.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_MOUVEMENTSDESTOCKS_EN 		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-liste-des-mouvements-de-stocks.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_MOUVEMENTSDESTOCKS_FR 		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-liste-des-mouvements-de-stocks.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_TRANSACTIONS_DUN_FOURNISSEUR_EN FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-transactions-dun-fournisseur.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_TRANSACTIONS_DUN_FOURNISSEUR_FR FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-transactions-dun-fournisseur.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTE_ADMIN_OBJECTS_EN 		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-lister-admin-objects.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTE_ADMIN_OBJECTS_FR 		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-lister-admin-objects.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_TRANSACTIONS_DUN_CLIENT_EN 		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-transactions-dun-client.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_TRANSACTIONS_DUN_CLIENT_FR 		FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-transactions-dun-client.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_FOURNISSEURS_EN 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-fournisseurs.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_FOURNISSEURS_FR 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-fournisseurs.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_COMPTES_CLIENTS_EN 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-comptes-clients.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_COMPTES_CLIENTS_FR 					FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-comptes-clients.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_MARCHANDISES_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-marchandises.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_MARCHANDISES_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-marchandises.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTE_ALERTES_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-lister-alertes.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTE_ALERTES_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-lister-alertes.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_CHARGES_FINANCIERES_EN 			FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-lister-charges-financieres.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_CHARGES_FINANCIERES_FR 			FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-lister-charges-financieres.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTE_ACHATS_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-lister-achats.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTE_ACHATS_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-lister-achats.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_COMPTABILITE_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-comptabilite.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_COMPTABILITE_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-comptabilite.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_THREE_D_BARDIAG						  FOLDER_YEROTH_ERP_3_0_TEMPLATES"/YEROTH-ERP-3D-BARDIAG-TEMPLATE.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_FICHE_STOCKS_EN 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-lister-stock.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_FICHE_STOCKS_FR 						FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-lister-stock.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTING_OUTGOING_STOCKS_SMALL_EN 	FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-sortie-des-stocks-petit.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTING_OUTGOING_STOCKS_SMALL_FR 	FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-sortie-des-stocks-petit.tex"

#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTING_OUTGOING_STOCKS_LARGE_EN 	FOLDER_YEROTH_ERP_3_0_TEMPLATES"/EN_template-sortie-des-stocks-grand.tex"
#define FILE_YEROTH_ERP_3_0_TEMPLATE_LISTING_OUTGOING_STOCKS_LARGE_FR 	FOLDER_YEROTH_ERP_3_0_TEMPLATES"/FR_template-sortie-des-stocks-grand.tex"


#endif //_YEROTH_ERP_3_0_DEFINITION_FILE_FOLDER_HPP_
