/*
 * yeroth-erp-3-0-definition-user-manual.hpp
 *
 *      Author: DR.-ING. DIPL.-INF. XAVIER NOUMBISSI NOUNDOU
 */

#ifndef _YEROTH_ERP_3_0_DEFINITION_USER_MANUAL_HPP_
#define _YEROTH_ERP_3_0_DEFINITION_USER_MANUAL_HPP_

#include "yeroth-erp-3-0-software.text-configuration.hpp"

#define FOLDER_YEROTH_ERP_3_0_USER_DOC 										"../../usr/share/doc/yeroth-erp-3-0"

#define FOLDER_YEROTH_ERP_3_0_USER_DOC_EN 									FOLDER_YEROTH_ERP_3_0_USER_DOC"/english"
#define FOLDER_YEROTH_ERP_3_0_USER_DOC_FR 									FOLDER_YEROTH_ERP_3_0_USER_DOC"/francais"

#define FILE_YEROTH_ERP_3_0_MANUEL_DE_LUTILISATEUR_MANAGER 					FOLDER_YEROTH_ERP_3_0_USER_DOC_FR"/JH_NISSI_ERP_PGI_COMPENDIUM.pdf"
#define FILE_YEROTH_ERP_3_0_MANUEL_DE_LUTILISATEUR_MANAGER_EN 			FOLDER_YEROTH_ERP_3_0_USER_DOC_EN"/JH_NISSI_ERP_PGI_COMPENDIUM.pdf"

#endif //_YEROTH_ERP_3_0_DEFINITION_USER_MANUAL_HPP_
