/*
 * yeroth-erp-3-0-definition-month.hpp
 *
 *      Author: DR.-ING. DIPL.-INF. XAVIER NOUMBISSI NOUNDOU
 */

#ifndef _YEROTH_ERP_3_0_DEFINITION_MONTH_HPP_
#define _YEROTH_ERP_3_0_DEFINITION_MONTH_HPP_

#define MONTH_YEROTH_ERP_3_0_JANUARY_EN	"January"
#define MONTH_YEROTH_ERP_3_0_JANUARY_FR 	"Janvier"

#define MONTH_YEROTH_ERP_3_0_FEBRUARY_EN 	"February"
#define MONTH_YEROTH_ERP_3_0_FEBRUARY_FR 	"Février"

#define MONTH_YEROTH_ERP_3_0_MARCH_EN 	"March"
#define MONTH_YEROTH_ERP_3_0_MARCH_FR 	"Mars"

#define MONTH_YEROTH_ERP_3_0_APRIL_EN 	"April"
#define MONTH_YEROTH_ERP_3_0_APRIL_FR 	"Avril"

#define MONTH_YEROTH_ERP_3_0_MAY_EN 	"May"
#define MONTH_YEROTH_ERP_3_0_MAY_FR 	"Mai"

#define MONTH_YEROTH_ERP_3_0_JUNE_EN 	"June"
#define MONTH_YEROTH_ERP_3_0_JUNE_FR 	"Juin"

#define MONTH_YEROTH_ERP_3_0_JULY_EN 	"July"
#define MONTH_YEROTH_ERP_3_0_JULY_FR 	"Juillet"

#define MONTH_YEROTH_ERP_3_0_AUGUST_EN 	"August"
#define MONTH_YEROTH_ERP_3_0_AUGUST_FR 	"Aôut"

#define MONTH_YEROTH_ERP_3_0_SEPTEMBER_EN	"September"
#define MONTH_YEROTH_ERP_3_0_SEPTEMBER_FR 	"Septembre"

#define MONTH_YEROTH_ERP_3_0_OCTOBER_EN 	"October"
#define MONTH_YEROTH_ERP_3_0_OCTOBER_FR 	"Octobre"

#define MONTH_YEROTH_ERP_3_0_NOVEMBER_EN 	"November"
#define MONTH_YEROTH_ERP_3_0_NOVEMBER_FR 	"Novembre"

#define MONTH_YEROTH_ERP_3_0_DECEMBER_EN 	"December"
#define MONTH_YEROTH_ERP_3_0_DECEMBER_FR 	"Décembre"

#endif //_YEROTH_ERP_3_0_DEFINITION_MONTH_HPP_
